idf_component_register(
    SRCS "src/bsp_display.c" "src/bsp_display_lvgl.c"
         "src/display_power_sequence.c" "src/display_lifecycle.c"
         "src/bsp_i2c.c" "src/bsp_battery.c"
         "src/bsp_button.c" "src/button_gesture.c"
    INCLUDE_DIRS "include"
    REQUIRES driver esp_driver_i2c esp_lcd esp_lvgl_port button esp_adc esp_timer
)
